server:
  port: 3355

config:
  info: "master branch,springcloud-config/config-prod3355.yml version=3"

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
